# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /projects/oat-parser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /projects/oat-parser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /projects/oat-parser/CMakeFiles /projects/oat-parser/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /projects/oat-parser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named oatparser

# Build rule for target.
oatparser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oatparser
.PHONY : oatparser

# fast build rule for target.
oatparser/fast:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/build
.PHONY : oatparser/fast

StringPiece.o: StringPiece.cpp.o

.PHONY : StringPiece.o

# target to build an object file
StringPiece.cpp.o:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/StringPiece.cpp.o
.PHONY : StringPiece.cpp.o

StringPiece.i: StringPiece.cpp.i

.PHONY : StringPiece.i

# target to preprocess a source file
StringPiece.cpp.i:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/StringPiece.cpp.i
.PHONY : StringPiece.cpp.i

StringPiece.s: StringPiece.cpp.s

.PHONY : StringPiece.s

# target to generate assembly for a file
StringPiece.cpp.s:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/StringPiece.cpp.s
.PHONY : StringPiece.cpp.s

art/compiler_filter.o: art/compiler_filter.cpp.o

.PHONY : art/compiler_filter.o

# target to build an object file
art/compiler_filter.cpp.o:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/art/compiler_filter.cpp.o
.PHONY : art/compiler_filter.cpp.o

art/compiler_filter.i: art/compiler_filter.cpp.i

.PHONY : art/compiler_filter.i

# target to preprocess a source file
art/compiler_filter.cpp.i:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/art/compiler_filter.cpp.i
.PHONY : art/compiler_filter.cpp.i

art/compiler_filter.s: art/compiler_filter.cpp.s

.PHONY : art/compiler_filter.s

# target to generate assembly for a file
art/compiler_filter.cpp.s:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/art/compiler_filter.cpp.s
.PHONY : art/compiler_filter.cpp.s

elf/elfloader.o: elf/elfloader.cpp.o

.PHONY : elf/elfloader.o

# target to build an object file
elf/elfloader.cpp.o:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/elf/elfloader.cpp.o
.PHONY : elf/elfloader.cpp.o

elf/elfloader.i: elf/elfloader.cpp.i

.PHONY : elf/elfloader.i

# target to preprocess a source file
elf/elfloader.cpp.i:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/elf/elfloader.cpp.i
.PHONY : elf/elfloader.cpp.i

elf/elfloader.s: elf/elfloader.cpp.s

.PHONY : elf/elfloader.s

# target to generate assembly for a file
elf/elfloader.cpp.s:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/elf/elfloader.cpp.s
.PHONY : elf/elfloader.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/main.cpp.s
.PHONY : main.cpp.s

oat/OATHeader.o: oat/OATHeader.cpp.o

.PHONY : oat/OATHeader.o

# target to build an object file
oat/OATHeader.cpp.o:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/oat/OATHeader.cpp.o
.PHONY : oat/OATHeader.cpp.o

oat/OATHeader.i: oat/OATHeader.cpp.i

.PHONY : oat/OATHeader.i

# target to preprocess a source file
oat/OATHeader.cpp.i:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/oat/OATHeader.cpp.i
.PHONY : oat/OATHeader.cpp.i

oat/OATHeader.s: oat/OATHeader.cpp.s

.PHONY : oat/OATHeader.s

# target to generate assembly for a file
oat/OATHeader.cpp.s:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/oat/OATHeader.cpp.s
.PHONY : oat/OATHeader.cpp.s

oat/OATParser.o: oat/OATParser.cpp.o

.PHONY : oat/OATParser.o

# target to build an object file
oat/OATParser.cpp.o:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/oat/OATParser.cpp.o
.PHONY : oat/OATParser.cpp.o

oat/OATParser.i: oat/OATParser.cpp.i

.PHONY : oat/OATParser.i

# target to preprocess a source file
oat/OATParser.cpp.i:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/oat/OATParser.cpp.i
.PHONY : oat/OATParser.cpp.i

oat/OATParser.s: oat/OATParser.cpp.s

.PHONY : oat/OATParser.s

# target to generate assembly for a file
oat/OATParser.cpp.s:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/oat/OATParser.cpp.s
.PHONY : oat/OATParser.cpp.s

zlib/adler32.o: zlib/adler32.c.o

.PHONY : zlib/adler32.o

# target to build an object file
zlib/adler32.c.o:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/zlib/adler32.c.o
.PHONY : zlib/adler32.c.o

zlib/adler32.i: zlib/adler32.c.i

.PHONY : zlib/adler32.i

# target to preprocess a source file
zlib/adler32.c.i:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/zlib/adler32.c.i
.PHONY : zlib/adler32.c.i

zlib/adler32.s: zlib/adler32.c.s

.PHONY : zlib/adler32.s

# target to generate assembly for a file
zlib/adler32.c.s:
	$(MAKE) -f CMakeFiles/oatparser.dir/build.make CMakeFiles/oatparser.dir/zlib/adler32.c.s
.PHONY : zlib/adler32.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... oatparser"
	@echo "... edit_cache"
	@echo "... StringPiece.o"
	@echo "... StringPiece.i"
	@echo "... StringPiece.s"
	@echo "... art/compiler_filter.o"
	@echo "... art/compiler_filter.i"
	@echo "... art/compiler_filter.s"
	@echo "... elf/elfloader.o"
	@echo "... elf/elfloader.i"
	@echo "... elf/elfloader.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... oat/OATHeader.o"
	@echo "... oat/OATHeader.i"
	@echo "... oat/OATHeader.s"
	@echo "... oat/OATParser.o"
	@echo "... oat/OATParser.i"
	@echo "... oat/OATParser.s"
	@echo "... zlib/adler32.o"
	@echo "... zlib/adler32.i"
	@echo "... zlib/adler32.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

